// AUTO-GENERATED by scripts/upload-to-cloudinary.cjs — do not edit by hand
export const LIFE_GALLERY_PUBLIC_IDS = [
  "rd-abacus-nadiad/life/IMG_0909",
  "rd-abacus-nadiad/life/IMG_0911",
  "rd-abacus-nadiad/life/IMG_0912",
  "rd-abacus-nadiad/life/IMG_0913",
  "rd-abacus-nadiad/life/IMG_0915",
  "rd-abacus-nadiad/life/IMG_0916",
  "rd-abacus-nadiad/life/IMG_0918",
  "rd-abacus-nadiad/life/IMG_0919",
  "rd-abacus-nadiad/life/IMG_0920",
] as const;
